# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tagged}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["toastyapps"]
  s.date = %q{2009-12-21}
  s.description = %q{Simple ORM agnostic tagging.}
  s.email = %q{matt@toastyapps.com}
  s.files = [
    ".gitignore",
     "Rakefile",
     "VERSION",
     "generators/tagged_migration/tagged_migration_generator.rb",
     "generators/tagged_migration/templates/migration.rb",
     "lib/tagged.rb",
     "lib/tagged/adapters/abstract_adapter.rb",
     "lib/tagged/adapters/active_record_adapter.rb",
     "lib/tagged/adapters/mongo_mapper_adapter.rb",
     "lib/tagged/tag.rb",
     "lib/tagged/tag_list.rb",
     "lib/tagged/tagging.rb",
     "rails/init.rb",
     "test/active_record_test.rb",
     "test/delimiter_test.rb",
     "test/mongo_mapper_schema.rb",
     "test/mongo_mapper_test.rb",
     "test/schema.rb",
     "test/tag_list_test.rb",
     "test/tagging_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/toastyapps/tagged}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple ORM agnostic tagging.}
  s.test_files = [
    "test/active_record_test.rb",
     "test/delimiter_test.rb",
     "test/mongo_mapper_schema.rb",
     "test/mongo_mapper_test.rb",
     "test/schema.rb",
     "test/tag_list_test.rb",
     "test/tagging_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

